### ISSUE TITLE
Add a new place for processing

### ISSUE THREAD

**Issue by mjwall** [NationalSecurityAgency/emissary#1]
Maybe PDF processing using Tika.  Could be nice example of how to add a place

**Comment by chrismattmann** [comment]
@mjwall very interesting! if you have any questions about Tika [we'd](@tballison) would be happy to help.

**Comment by mjwall** [comment]
Thanks @chrismattmann.  Would love to talk Tika at some point.

**Comment by chrismattmann** [comment]
firstname.lastname@gmail.com for me feel free to reach out @mjwall
