### ISSUE TITLE
Fix Undesired Duplicate Place Visits

### ISSUE THREAD

**Issue by LightSeekerSC** [NationalSecurityAgency/emissary#110]
Currently, Emissary is designed so that any item going through a transform place will go back to the study phase. This requires every transform place to force a form change or otherwise be at risk of an infinite loop.

It would be preferable that BaseDataObjects are intelligent enough to not loop back to the same place if their form has not changed since their last visit. This can be accomplished by caching places visited with the current form and refreshing this every time the form is changed

**Comment by ggambrell** [comment]
Work will be reprioritized under a new ticket.
