### ISSUE TITLE
IBDO Function For Creating Child IBDO

### ISSUE THREAD

**Issue by LightSeekerSC** [NationalSecurityAgency/emissary#111]
Creating a standardized function for creating a child of the IBDO will allow us to have centralized, consistent processing logic that will reduce risk of manually coded processing errors and enhance developer velocity

This function will also allow for the IBDO to better track the number of descendants and could better consolidate logic that needs to be synchronized for proper multi-threading (e.g. locking the update of descendant count)

**Comment by ggambrell** [comment]
Work will be reprioritized under the linked or a new ticket.
