### ISSUE TITLE
Off-heap/high capacity base data objects

### ISSUE THREAD

**Issue by adyoun2** [NationalSecurityAgency/emissary#12]
There are 3 intents:

1. If configured, it is possible that BaseDataObjects could be backed externally to the heap (files or off heap memory), allowing a lower memory footprint for objects not actively being processed.
2. Data objects are not limited to being 2GB.
3. All changes are compatible with existing bytecode.

**Comment by ukengineer925** [comment]
Believe this can now be closed since #204 has been merged in and released with emissary 7.11.0.
