### ISSUE TITLE
Do not allow duplicate forms in the form stack on IBDO

### ISSUE THREAD

**Issue by andrewbp** [NationalSecurityAgency/emissary#180]
"I believe the idea here is that there should never be cause to add a form that already exists on the form stack a second time. Once a form is handled it would probably be inappropriate or erroneous to revisit that form.

confirm this is possible
prevent forms matching a form that already exists in the list of forms from being added (enqueueForm method does this?)
add a log (warn?) message that alerts us to an attempt to add a duplicate form so we could investigate the origin

ibdo.pushCurrentForm allows for duplicate forms to be placed in the list."
-justin-c-4

**Comment by drewfarris** [comment]
> I believe the idea here is that there should never be cause to add a form that already exists on the form stack a second time. 

What about nested archive files, e.g.: a zip file within a zip file?

**Comment by drivenflywheel** [comment]
> What about nested archive files, e.g.: a zip file within a zip file?

Wouldn't those files map to separate IBDO instances?
