### ISSUE TITLE
ByteMatcher & KeywordScanner needs set/reset ability

### ISSUE THREAD

**Issue by apmoriarty** [NationalSecurityAgency/emissary#25]
In cases where the ByteMatcher and KeywordScanner need to operate on new data, the objects need to be entirely re-initialized. A simple "set/reset" method to update the bytes these classes operate on would avoid re-initializing these objects each time.

**Comment by jpdahlke** [comment]
done via https://github.com/NationalSecurityAgency/emissary/pull/26
