### ISSUE TITLE
Security Contact

### ISSUE THREAD

**Issue by johannes-dahse-sonarsource** [NationalSecurityAgency/emissary#86]
Hello emissary team,

we have found a couple of security vulnerabilities in the emissary source code that we would like to report.

What's the best way to privately report these bugs?

Thank you,
Johannes

**Comment by ctubbsii** [comment]
Hi @johannes-dahse-sonarsource . For now, you can email me at `christopher` dot `tubbs` dot `civ` at `mail` dot `mil` and I can make sure it gets passed along to the right team members. I'll close this issue for now.

**Comment by jpdahlke** [comment]
Some updates have been made to address issues based on the provided feedback and a new version has been released. 

https://github.com/NationalSecurityAgency/emissary/releases/tag/5.11.0

Thank you and feel free to reach out to EmissarySupport@evoforge.org with any further questions.

**Comment by johannes-dahse-sonarsource** [comment]
Hello, 
thank you for the update. We tried to followup with questions but are receiving the following error when reaching out to this new email:
`Your message couldn't be delivered because delivery to this group is restricted to authenticated senders.`
Best,
Johannes

**Comment by jpdahlke** [comment]
Thank you. We are investigating this issue.

**Comment by jpdahlke** [comment]
@johannes-dahse-sonarsource the issue with our email alias should be resolved.
